// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkwscXBn4h0-VabM7X0379g8VdVi2l-E8',
    appId: '1:69159088182:web:e3fcf52e7da4fe3a38e897',
    messagingSenderId: '69159088182',
    projectId: 'tflite-server-67532',
    authDomain: 'tflite-server-67532.firebaseapp.com',
    storageBucket: 'tflite-server-67532.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbAdfuIPPI7Ic7gawbhtaQUSTByfOOumQ',
    appId: '1:69159088182:android:7bd722c51d8c15b738e897',
    messagingSenderId: '69159088182',
    projectId: 'tflite-server-67532',
    storageBucket: 'tflite-server-67532.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLpWCXmiTqFotvs7tAkJTZxtQivU5l_1I',
    appId: '1:69159088182:ios:e420496cfa7c93cf38e897',
    messagingSenderId: '69159088182',
    projectId: 'tflite-server-67532',
    storageBucket: 'tflite-server-67532.firebasestorage.app',
    iosBundleId: 'com.example.yoloDetect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLpWCXmiTqFotvs7tAkJTZxtQivU5l_1I',
    appId: '1:69159088182:ios:e420496cfa7c93cf38e897',
    messagingSenderId: '69159088182',
    projectId: 'tflite-server-67532',
    storageBucket: 'tflite-server-67532.firebasestorage.app',
    iosBundleId: 'com.example.yoloDetect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkwscXBn4h0-VabM7X0379g8VdVi2l-E8',
    appId: '1:69159088182:web:0325cd7d5635303438e897',
    messagingSenderId: '69159088182',
    projectId: 'tflite-server-67532',
    authDomain: 'tflite-server-67532.firebaseapp.com',
    storageBucket: 'tflite-server-67532.firebasestorage.app',
  );
}
